import {
	createLeaseDocumentContract,
	createTenantDocumentContract,
	createUnitDocumentContract,
	deleteLeaseDocumentContract,
	deleteTenantDocumentContract,
	deleteUnitDocumentContract,
	getLeaseDocumentContract,
	getTenantDocumentContract,
	getUnitDocumentContract,
	listLeaseDocumentContract,
	listTenantDocumentContract,
	listUnitDocumentContract,
	supersededLeaseDocumentContract,
	supersededUnitDocumentContract,
	updateLeaseDocumentContract,
	updateTenantDocumentContract,
	updateUnitDocumentContract,
} from "./document.contract";
import {
	completeInspectionContract,
	createInspectionContract,
	deleteInspectionContract,
	getInspectionContract,
	listInspectionContract,
	skipInspectionContract,
	updateInspectionContract,
} from "./inspection.contract";
import {
	createLeaseContract,
	createLeaseRentContract,
	deleteLeaseRentContract,
	getLeaseContract,
	listLeaseContract,
	listLeaseRentContract,
	deleteLeaseContract,
	updateLeaseContract,
	updateLeaseRentContract,
	renewLeaseContract,
} from "./lease.contract";
import {
	createPaymentContract,
	getPaymentContract,
	getReceiptContract,
	listPaymentContract,
	listReceiptsContract,
	updatePaymentContract,
} from "./payment.contract";
import {
	addRepairUpdateContract,
	createRepairRequestContract,
	deleteRepairRequestContract,
	getRepairRequestContract,
	listRepairRequestContract,
	listRepairUpdatesContract,
	updateRepairRequestContract,
} from "./repair.contract";
import {
	arrearsOverviewContract,
	expiringDocumentsContract,
	expiringLeasesContract,
	occupancySummaryContract,
	overdueUtilityBillsContract,
	rentCollectionContract,
	repairSummaryContract,
	upcomingInspectionsContract,
	upcomingRentDueContract,
} from "./report.contract";
import {
	createTenantContract,
	deleteTenantContract,
	getTenantContract,
	listTenantContract,
	updateTenantContract,
	createTenantOccupantContract,
	updateTenantOccupantContract,
	deleteTenantOccupantContract,
	listTenantOccupantContract,
} from "./tenant.contract";
import {
	createUnitContract,
	deleteUnitContract,
	getUnitContract,
	listUnitContract,
	updateUnitContract,
} from "./unit.contract";
import {
	createUtilityBillContract,
	createUtilityContract,
	deactivateUtilityContract,
	deleteUtilityBillContract,
	deleteUtilityContract,
	listUtilityBillContract,
	listUtilityContract,
	markUtilityBillPaidContract,
	updateUtilityBillContract,
	updateUtilityContract,
} from "./utility.contract";

export const contract = {
	unit: {
		create: createUnitContract,
		update: updateUnitContract,
		delete: deleteUnitContract,
		get: getUnitContract,
		list: listUnitContract,
	},
	tenant: {
		create: createTenantContract,
		update: updateTenantContract,
		delete: deleteTenantContract,
		get: getTenantContract,
		list: listTenantContract,
		createOccupant: createTenantOccupantContract,
		updateOccupant: updateTenantOccupantContract,
		deleteOccupant: deleteTenantOccupantContract,
		listOccupants: listTenantOccupantContract,
	},
	lease: {
		create: createLeaseContract,
		update: updateLeaseContract,
		renew: renewLeaseContract,
		delete: deleteLeaseContract,
		get: getLeaseContract,
		list: listLeaseContract,
		createRent: createLeaseRentContract,
		updateRent: updateLeaseRentContract,
		deleteRent: deleteLeaseRentContract,
		listRents: listLeaseRentContract,
	},
	payment: {
		create: createPaymentContract,
		update: updatePaymentContract,
		get: getPaymentContract,
		list: listPaymentContract,
		getReceipt: getReceiptContract,
		listReceipts: listReceiptsContract,
	},
	utility: {
		create: createUtilityContract,
		update: updateUtilityContract,
		deactivate: deactivateUtilityContract,
		delete: deleteUtilityContract,
		list: listUtilityContract,
		createBill: createUtilityBillContract,
		updateBill: updateUtilityBillContract,
		markBillPaid: markUtilityBillPaidContract,
		deleteBill: deleteUtilityBillContract,
		listBills: listUtilityBillContract,
	},
	repair: {
		create: createRepairRequestContract,
		update: updateRepairRequestContract,
		delete: deleteRepairRequestContract,
		get: getRepairRequestContract,
		list: listRepairRequestContract,
		addUpdate: addRepairUpdateContract,
		listUpdates: listRepairUpdatesContract,
	},
	inspection: {
		create: createInspectionContract,
		update: updateInspectionContract,
		complete: completeInspectionContract,
		skip: skipInspectionContract,
		delete: deleteInspectionContract,
		get: getInspectionContract,
		list: listInspectionContract,
	},
	document: {
		createUnit: createUnitDocumentContract,
		updateUnit: updateUnitDocumentContract,
		supersedeUnit: supersededUnitDocumentContract,
		getUnit: getUnitDocumentContract,
		deleteUnit: deleteUnitDocumentContract,
		listUnit: listUnitDocumentContract,
		createTenant: createTenantDocumentContract,
		updateTenant: updateTenantDocumentContract,
		getTenant: getTenantDocumentContract,
		deleteTenant: deleteTenantDocumentContract,
		listTenant: listTenantDocumentContract,
		createLease: createLeaseDocumentContract,
		updateLease: updateLeaseDocumentContract,
		supersedeLease: supersededLeaseDocumentContract,
		deleteLease: deleteLeaseDocumentContract,
		getLease: getLeaseDocumentContract,
		listLease: listLeaseDocumentContract,
	},
	report: {
		occupancySummary: occupancySummaryContract,
		rentCollection: rentCollectionContract,
		arrearsOverview: arrearsOverviewContract,
		upcomingRentDue: upcomingRentDueContract,
		expiringDocuments: expiringDocumentsContract,
		upcomingInspections: upcomingInspectionsContract,
		overdueUtilityBills: overdueUtilityBillsContract,
		repairSummary: repairSummaryContract,
		expiringLeases: expiringLeasesContract,
	},
};
