import { implement } from "@orpc/server";
import { contract } from "../contract";
import {
	createLeaseDocument,
	createTenantDocument,
	createUnitDocument,
	deleteLeaseDocument,
	deleteTenantDocument,
	deleteUnitDocument,
	getLeaseDocument,
	getTenantDocument,
	getUnitDocument,
	listLeaseDocument,
	listTenantDocument,
	listUnitDocument,
	supersededLeaseDocument,
	supersededUnitDocument,
	updateLeaseDocument,
	updateTenantDocument,
	updateUnitDocument,
} from "./document";
import {
	completeInspection,
	createInspection,
	deleteInspection,
	getInspection,
	listInspection,
	skipInspection,
	updateInspection,
} from "./inspection";
import {
	createLease,
	createLeaseRent,
	deleteLease,
	deleteLeaseRent,
	getLease,
	listLease,
	listLeaseRent,
	renewLease,
	updateLease,
	updateLeaseRent,
} from "./lease";
import type { BaseContext } from "./middleware";
import {
	bulkUpsertNotificationPreferences,
	deleteNotificationPreference,
	listNotificationLogs,
	listNotificationPreferences,
	markAllNotificationsRead,
	markNotificationRead,
	upsertNotificationPreference,
} from "./notification";
import {
	createPayment,
	getPayment,
	listPayment,
	nextRentMonth,
	updatePayment,
} from "./payment";
import {
	addRepairUpdate,
	createRepairRequest,
	deleteRepairRequest,
	getRepairRequest,
	listRepairRequest,
	listRepairUpdates,
	updateRepairRequest,
} from "./repair";
import {
	arrearsOverview,
	expiringDocuments,
	expiringLeases,
	occupancySummary,
	overdueUtilityBills,
	paymentOverview,
	rentCollection,
	repairSummary,
	upcomingInspections,
	upcomingRentDue,
} from "./report";
import {
	createTenant,
	createTenantOccupant,
	deleteTenant,
	deleteTenantOccupant,
	getTenant,
	listTenant,
	listTenantOccupant,
	updateTenant,
	updateTenantOccupant,
} from "./tenant";
import { createUnit, deleteUnit, getUnit, listUnit, updateUnit } from "./unit";
import {
	approveUser,
	deleteUserAccount,
	getMyUserProfile,
	listAvailableTenantsForApproval,
	listUsers,
	revokeUserAccess,
	updateMyUserProfile,
	updateUserRole,
} from "./user";
import {
	createUtility,
	createUtilityBill,
	deactivateUtility,
	deleteUtility,
	deleteUtilityBill,
	listUtility,
	listUtilityBill,
	markUtilityBillPaid,
	updateUtility,
	updateUtilityBill,
} from "./utility";

const os = implement(contract).$context<BaseContext>();

export const router = os.router({
	unit: {
		create: createUnit,
		update: updateUnit,
		delete: deleteUnit,
		get: getUnit,
		list: listUnit,
	},
	tenant: {
		create: createTenant,
		update: updateTenant,
		delete: deleteTenant,
		get: getTenant,
		list: listTenant,
		createOccupant: createTenantOccupant,
		updateOccupant: updateTenantOccupant,
		deleteOccupant: deleteTenantOccupant,
		listOccupants: listTenantOccupant,
	},
	lease: {
		create: createLease,
		update: updateLease,
		delete: deleteLease,
		renew: renewLease,
		get: getLease,
		list: listLease,
		createRent: createLeaseRent,
		updateRent: updateLeaseRent,
		deleteRent: deleteLeaseRent,
		listRents: listLeaseRent,
	},
	payment: {
		create: createPayment,
		update: updatePayment,
		get: getPayment,
		list: listPayment,
		nextRentMonth: nextRentMonth,
	},
	utility: {
		create: createUtility,
		update: updateUtility,
		deactivate: deactivateUtility,
		delete: deleteUtility,
		list: listUtility,
		createBill: createUtilityBill,
		updateBill: updateUtilityBill,
		markBillPaid: markUtilityBillPaid,
		deleteBill: deleteUtilityBill,
		listBills: listUtilityBill,
	},
	repair: {
		create: createRepairRequest,
		update: updateRepairRequest,
		delete: deleteRepairRequest,
		get: getRepairRequest,
		list: listRepairRequest,
		addUpdate: addRepairUpdate,
		listUpdates: listRepairUpdates,
	},
	inspection: {
		create: createInspection,
		update: updateInspection,
		complete: completeInspection,
		skip: skipInspection,
		delete: deleteInspection,
		get: getInspection,
		list: listInspection,
	},
	document: {
		createUnit: createUnitDocument,
		updateUnit: updateUnitDocument,
		supersedeUnit: supersededUnitDocument,
		getUnit: getUnitDocument,
		deleteUnit: deleteUnitDocument,
		listUnit: listUnitDocument,
		createTenant: createTenantDocument,
		updateTenant: updateTenantDocument,
		deleteTenant: deleteTenantDocument,
		getTenant: getTenantDocument,
		listTenant: listTenantDocument,
		createLease: createLeaseDocument,
		updateLease: updateLeaseDocument,
		supersedeLease: supersededLeaseDocument,
		deleteLease: deleteLeaseDocument,
		getLease: getLeaseDocument,
		listLease: listLeaseDocument,
	},
	report: {
		occupancySummary: occupancySummary,
		rentCollection: rentCollection,
		paymentOverview: paymentOverview,
		arrearsOverview: arrearsOverview,
		upcomingRentDue: upcomingRentDue,
		expiringDocuments: expiringDocuments,
		upcomingInspections: upcomingInspections,
		overdueUtilityBills: overdueUtilityBills,
		repairSummary: repairSummary,
		expiringLeases: expiringLeases,
	},
	notification: {
		upsert: upsertNotificationPreference,
		bulkUpsert: bulkUpsertNotificationPreferences,
		deletePreference: deleteNotificationPreference,
		listPreferences: listNotificationPreferences,
		listLogs: listNotificationLogs,
		markRead: markNotificationRead,
		markAllRead: markAllNotificationsRead,
	},
	user: {
		list: listUsers,
		me: getMyUserProfile,
		updateMe: updateMyUserProfile,
		approve: approveUser,
		updateRole: updateUserRole,
		revokeAccess: revokeUserAccess,
		delete: deleteUserAccount,
		listAvailableTenants: listAvailableTenantsForApproval,
	},
});
