import { implement } from "@orpc/server";
import { contract } from "../contract";
import { BaseContext } from "./middleware";
import { createUnit, deleteUnit, getUnit, listUnit, updateUnit } from "./unit";
import {
	createTenant,
	deleteTenant,
	getTenant,
	listTenant,
	updateTenant,
	createTenantOccupant,
	updateTenantOccupant,
	deleteTenantOccupant,
	listTenantOccupant,
} from "./tenant";
import {
	createLease,
	getLease,
	listLease,
	listLeaseRent,
	deleteLease,
	updateLease,
	deleteLeaseRent,
	createLeaseRent,
	updateLeaseRent,
	renewLease,
} from "./lease";
import {
	createPayment,
	getPayment,
	getReceipt,
	listPayment,
	listReceipts,
	updatePayment,
} from "./payment";
import {
	createUtility,
	createUtilityBill,
	deactivateUtility,
	deleteUtility,
	deleteUtilityBill,
	listUtility,
	listUtilityBill,
	markUtilityBillPaid,
	updateUtility,
	updateUtilityBill,
} from "./utility";
import {
	addRepairUpdate,
	createRepairRequest,
	deleteRepairRequest,
	getRepairRequest,
	listRepairRequest,
	listRepairUpdates,
	updateRepairRequest,
} from "./repair";
import {
	completeInspection,
	createInspection,
	deleteInspection,
	getInspection,
	listInspection,
	skipInspection,
	updateInspection,
} from "./inspection";
import {
	createLeaseDocument,
	createTenantDocument,
	createUnitDocument,
	deleteLeaseDocument,
	deleteTenantDocument,
	deleteUnitDocument,
	getLeaseDocument,
	getTenantDocument,
	getUnitDocument,
	listLeaseDocument,
	listTenantDocument,
	listUnitDocument,
	supersededLeaseDocument,
	supersededUnitDocument,
	updateLeaseDocument,
	updateTenantDocument,
	updateUnitDocument,
} from "./document";

const os = implement(contract).$context<BaseContext>();

export const router = os.router({
	unit: {
		create: createUnit,
		update: updateUnit,
		delete: deleteUnit,
		get: getUnit,
		list: listUnit,
	},
	tenant: {
		create: createTenant,
		update: updateTenant,
		delete: deleteTenant,
		get: getTenant,
		list: listTenant,
		createOccupant: createTenantOccupant,
		updateOccupant: updateTenantOccupant,
		deleteOccupant: deleteTenantOccupant,
		listOccupants: listTenantOccupant,
	},
	lease: {
		create: createLease,
		update: updateLease,
		delete: deleteLease,
		renew: renewLease,
		get: getLease,
		list: listLease,
		createRent: createLeaseRent,
		updateRent: updateLeaseRent,
		deleteRent: deleteLeaseRent,
		listRents: listLeaseRent,
	},
	payment: {
		create: createPayment,
		update: updatePayment,
		get: getPayment,
		list: listPayment,
		getReceipt: getReceipt,
		listReceipts: listReceipts,
	},
	utility: {
		create: createUtility,
		update: updateUtility,
		deactivate: deactivateUtility,
		delete: deleteUtility,
		list: listUtility,
		createBill: createUtilityBill,
		updateBill: updateUtilityBill,
		markBillPaid: markUtilityBillPaid,
		deleteBill: deleteUtilityBill,
		listBills: listUtilityBill,
	},
	repair: {
		create: createRepairRequest,
		update: updateRepairRequest,
		delete: deleteRepairRequest,
		get: getRepairRequest,
		list: listRepairRequest,
		addUpdate: addRepairUpdate,
		listUpdates: listRepairUpdates,
	},
	inspection: {
		create: createInspection,
		update: updateInspection,
		complete: completeInspection,
		skip: skipInspection,
		delete: deleteInspection,
		get: getInspection,
		list: listInspection,
	},
	document: {
		createUnit: createUnitDocument,
		updateUnit: updateUnitDocument,
		supersedeUnit: supersededUnitDocument,
		getUnit: getUnitDocument,
		deleteUnit: deleteUnitDocument,
		listUnit: listUnitDocument,
		createTenant: createTenantDocument,
		updateTenant: updateTenantDocument,
		deleteTenant: deleteTenantDocument,
		getTenant: getTenantDocument,
		listTenant: listTenantDocument,
		createLease: createLeaseDocument,
		updateLease: updateLeaseDocument,
		supersedeLease: supersededLeaseDocument,
		deleteLease: deleteLeaseDocument,
		getLease: getLeaseDocument,
		listLease: listLeaseDocument,
	},
});
