import { jsPDF } from "jspdf";
import type { ListPaymentOutput } from "@/app/schemas/payment.schema";
import {
	PAYMENT_METHOD_META,
	PAYMENT_TYPE_META,
} from "@/config/table-facet-meta";
import { formatCurrency, formatExportDate } from "./formatters";

type PaymentRow = ListPaymentOutput["items"][number];

function getReceiptCopy(paymentType: PaymentRow["paymentType"]) {
	switch (paymentType) {
		case "rent":
			return {
				title: "Rent Payment Receipt",
				statusLabel: "Received",
				note: "This receipt confirms rent was received and recorded.",
			};
		case "rent_waiver":
			return {
				title: "Rent Waiver Record",
				statusLabel: "Waived",
				note: "This document confirms rent for the period was waived and recorded.",
			};
		case "deposit":
			return {
				title: "Deposit Receipt",
				statusLabel: "Received as Deposit",
				note: "This receipt confirms a deposit payment was recorded.",
			};
		case "deposit_deduction":
			return {
				title: "Deposit Deduction Record",
				statusLabel: "Deducted from Deposit",
				note: "This document confirms a deduction was recorded against the lease deposit.",
			};
		case "arrear":
			return {
				title: "Arrears Payment Receipt",
				statusLabel: "Received as Arrears",
				note: "This receipt confirms an arrears payment was received and recorded.",
			};
		case "refund":
			return {
				title: "Refund Record",
				statusLabel: "Refunded",
				note: "This document confirms a refund was recorded.",
			};
		default:
			return {
				title: "Payment Record",
				statusLabel: "Recorded",
				note: "This document confirms the transaction was recorded in the system.",
			};
	}
}

export function downloadPaymentReceipt(
	payment: PaymentRow,
	generatedBy = "Rently system",
) {
	const doc = new jsPDF({
		unit: "pt",
		format: "a5",
	});

	const left = 28;
	const right = doc.internal.pageSize.width - 28;
	let y = 34;

	const paymentTypeLabel =
		PAYMENT_TYPE_META[payment.paymentType as keyof typeof PAYMENT_TYPE_META]
			?.label ?? payment.paymentType;

	const paymentMethodLabel =
		PAYMENT_METHOD_META[
			payment.paymentMethod as keyof typeof PAYMENT_METHOD_META
		]?.label ?? payment.paymentMethod;

	const receiptNumber = payment.receiptNumber ?? `PAY-${payment.id}`;
	const issuedDate = formatExportDate(new Date().toISOString());
	const receiptCopy = getReceiptCopy(payment.paymentType);
	const leaseSummary = payment.leaseSummary;
	const unitName = leaseSummary?.unitName ?? `Lease #${payment.leaseId}`;
	const unitAddress = leaseSummary?.unitAddress ?? "-";
	const tenantName = leaseSummary?.tenantName ?? "Tenant on lease record";
	const tenantPhoneNumber = leaseSummary?.tenantPhoneNumber ?? "-";
	const paidFor =
		payment.periodStart && payment.periodEnd
			? `${formatExportDate(payment.periodStart)} to ${formatExportDate(payment.periodEnd)}`
			: "Not applicable";

	doc.setFillColor(229, 139, 85);
	doc.roundedRect(left, y, right - left, 68, 10, 10, "F");

	doc.setTextColor(255, 255, 255);
	doc.setFontSize(18);
	doc.setFont("helvetica", "bold");
	doc.text(receiptCopy.title, left + 16, y + 24);

	doc.setFontSize(10);
	doc.setFont("helvetica", "normal");
	doc.text("Rently Property Management", left + 16, y + 42);
	// doc.text(`Generated by: ${generatedBy}`, left + 16, y + 56);

	doc.setFont("helvetica", "bold");
	doc.text(`${receiptNumber}`, right - 16, y + 24, {
		align: "right",
	});
	doc.setFont("helvetica", "normal");
	doc.text(`${issuedDate}`, right - 16, y + 42, {
		align: "right",
	});

	doc.setTextColor(20, 28, 45);
	y += 92;

	doc.setFontSize(11);
	doc.setFont("helvetica", "bold");
	doc.text("Lease and Tenant", left, y);

	y += 18;
	doc.setFont("helvetica", "normal");
	doc.text(unitName, left, y);
	doc.text(unitAddress, left, y + 14);
	doc.text(`${tenantName}`, left, y + 28);
	doc.text(`${tenantPhoneNumber}`, left, y + 42);

	y += 60;
	doc.setDrawColor(220, 220, 220);
	doc.line(left, y, right, y);

	y += 22;
	doc.setFont("helvetica", "bold");
	doc.text("Transaction Details", left, y);

	y += 14;
	const tableTop = y;
	const tableHeight = 42;
	const tableWidth = right - left;
	const colWidths = [72, 66, 64, 102, tableWidth - (72 + 66 + 64 + 102)];
	const headers = ["Payment Date", "Type", "Method", "Paid For", "Amount"];
	const values = [
		formatExportDate(payment.paymentDate),
		paymentTypeLabel,
		paymentMethodLabel,
		paidFor,
		formatCurrency(payment.paymentAmount),
	];

	doc.setDrawColor(210, 210, 210);
	doc.rect(left, tableTop, tableWidth, tableHeight);
	doc.line(left, tableTop + 18, right, tableTop + 18);

	let cursorX = left;
	for (let i = 0; i < colWidths.length - 1; i++) {
		cursorX += colWidths[i];
		doc.line(cursorX, tableTop, cursorX, tableTop + tableHeight);
	}

	cursorX = left;
	doc.setFontSize(8);
	doc.setFont("helvetica", "bold");
	for (let i = 0; i < headers.length; i++) {
		doc.text(headers[i], cursorX + 4, tableTop + 12);
		cursorX += colWidths[i];
	}

	cursorX = left;
	doc.setFont("helvetica", "normal");
	for (let i = 0; i < values.length; i++) {
		const clipped = String(values[i]).slice(0, 28);
		doc.text(clipped, cursorX + 4, tableTop + 32);
		cursorX += colWidths[i];
	}

	y = tableTop + tableHeight;

	y += 22;
	doc.setFontSize(11);
	doc.setFont("helvetica", "bold");
	doc.text("Description", left, y);

	y += 16;
	doc.setFont("helvetica", "normal");
	const description = payment.description?.trim() || "-";
	const wrappedDescription = doc.splitTextToSize(description, right - left);
	doc.text(wrappedDescription, left, y);

	y += wrappedDescription.length * 14 + 20;
	doc.setDrawColor(30, 30, 30);
	doc.line(left, y, right, y);

	y += 24;
	doc.setFont("helvetica", "bold");
	doc.setFontSize(13);
	doc.text(receiptCopy.statusLabel, left, y);
	doc.text(formatCurrency(payment.paymentAmount), right, y, { align: "right" });

	y += 28;
	doc.setFontSize(10);
	doc.setFont("helvetica", "normal");
	const wrappedNote = doc.splitTextToSize(receiptCopy.note, right - left);
	doc.text(wrappedNote, left, y);

	y += wrappedNote.length * 12 + 16;
	doc.setTextColor(90, 90, 90);
	doc.text(`Generated by ${generatedBy} on ${issuedDate}`, left, y);

	doc.save(`receipt-${receiptNumber}.pdf`);
}
